// ============================================================================
// DATA
// ============================================================================


export const ATTRS = {
  str: { name: 'Strength',     short: 'STR' },
  agl: { name: 'Agility',      short: 'AGL' },
  int: { name: 'Intelligence', short: 'INT' },
  emp: { name: 'Empathy',      short: 'EMP' },
};

export const SKILLS = {
  closeCombat:  { name: 'Close Combat',  attr: 'str' },
  heavyWeapons: { name: 'Heavy Weapons', attr: 'str' },
  stamina:      { name: 'Stamina',       attr: 'str' },
  rangedCombat: { name: 'Ranged Combat', attr: 'agl' },
  driving:      { name: 'Driving',       attr: 'agl' },
  mobility:     { name: 'Mobility',      attr: 'agl' },
  recon:        { name: 'Recon',         attr: 'int' },
  survival:     { name: 'Survival',      attr: 'int' },
  tech:         { name: 'Tech',          attr: 'int' },
  command:      { name: 'Command',       attr: 'emp' },
  medicalAid:   { name: 'Medical Aid',   attr: 'emp' },
  persuasion:   { name: 'Persuasion',    attr: 'emp' },
};

// Always available regardless of career
export const ALWAYS_AVAILABLE = ['stamina', 'mobility', 'driving'];

export const NATIONALITIES = [
  'American', 'British', 'Polish', 'Soviet (Russian)', 'Soviet (Ukrainian)',
  'German', 'Swedish', 'French', 'Czech', 'Other',
];

// 6 childhoods, indexed 1-6 for D6 roll
export const CHILDHOODS = [
  { id: 1, name: 'Affluent',
    blurb: 'Marble lobbies, summer houses, the kind of money that whispered. You learned manners and where to put your fork.',
    skills: ['persuasion', 'tech', 'command', 'driving'],
    specialties: ['Diplomat', 'Equestrian', 'Sailor', 'Polyglot', 'Marksman', 'Connoisseur'] },
  { id: 2, name: 'Rural',
    blurb: 'Mud and hay and a long walk to the school bus. You knew weather and animals before you knew much else.',
    skills: ['survival', 'stamina', 'driving', 'rangedCombat'],
    specialties: ['Farmer', 'Hunter', 'Survivalist', 'Outdoorsman', 'Rider', 'Tracker'] },
  { id: 3, name: 'Working Class',
    blurb: 'Concrete, sirens, the long bus ride home. You learned to read a room before you could read a book.',
    skills: ['persuasion', 'mobility', 'recon', 'closeCombat'],
    specialties: ['Streetwise', 'Brawler', 'Hustler', 'Driver', 'Athlete', 'Mechanic'] },
  { id: 4, name: 'Small Town',
    blurb: 'Diner, grain elevator, two churches and one stoplight. Everybody watching everybody.',
    skills: ['driving', 'persuasion', 'recon', 'tech'],
    specialties: ['Mechanic', 'Trader', 'Hometown Hero', 'Sportsman', 'Hunter', 'Driver'] },
  { id: 5, name: 'Intellectual',
    blurb: 'Books were the place you went when the world got too loud. You went often.',
    skills: ['tech', 'medicalAid', 'persuasion', 'recon'],
    specialties: ['Scholar', 'Linguist', 'Engineer', 'Pre-Med', 'Researcher', 'Journalist'] },
  { id: 6, name: 'Military Family',
    blurb: 'Born on base. Five schools by twelve. The colors went up at dawn and so did you.',
    skills: ['rangedCombat', 'closeCombat', 'command', 'stamina'],
    specialties: ['Brawler', 'Rifleman', 'Tactician', 'Quartermaster', 'Cadet', 'Linguist'] },
];

export const MILITARY_RANKS = {
  combat:    ['Private', 'PFC', 'Specialist', 'Corporal', 'Sergeant', 'Staff Sergeant', 'Sgt. First Class'],
  combatSupport: ['Private', 'PFC', 'Specialist', 'Corporal', 'Sergeant', 'Staff Sergeant'],
  logistics: ['Private', 'PFC', 'Specialist', 'Corporal', 'Sergeant'],
  specOps:   ['Private', 'Specialist', 'Corporal', 'Sergeant', 'Staff Sergeant', 'Sgt. First Class'],
  officer:   ['2nd Lieutenant', '1st Lieutenant', 'Captain', 'Major', 'Lt. Colonel', 'Colonel'],
  intel:     ['Junior Agent', 'Agent', 'Senior Agent', 'Special Agent', 'Station Chief'],
};

// Career groups (umbrellas) for display. Careers live under one of these.
export const CAREER_GROUPS = [
  { id: 'military',    name: 'Military',     blurb: 'Sworn in, kitted out, shipped out.' },
  { id: 'police',      name: 'Police',       blurb: 'Order in a world losing it.' },
  { id: 'crime',       name: 'Crime',        blurb: 'Off the books, by whatever means.' },
  { id: 'intel',       name: 'Intelligence', blurb: 'Cold War shadows that lingered.' },
  { id: 'blueCollar',  name: 'Blue Collar',  blurb: 'Hands, machines, honest work.' },
  { id: 'education',   name: 'Education',    blurb: 'Lecture halls and library stacks.' },
  { id: 'whiteCollar', name: 'White Collar', blurb: 'Offices, hospitals, civil service.' },
];

// Granular careers, each in one group. Each carries its own skills,
// specialty table (D6), and starting gear slots.
export const CAREERS = [
  // === MILITARY ===========================================================
  { id: 'combatArms', group: 'military', name: 'Combat Arms', military: true,
    blurb: 'Infantry, armor, artillery — the tip of the spear.',
    req: { str: 10 }, reqLabel: 'STR B+ Or AGL B+',
    skills: ['closeCombat', 'rangedCombat', 'heavyWeapons', 'recon'],
    specialties: ['Rifleman', 'Redleg', 'Tanker', 'Machinegunner', 'Launcher Crew', 'Combat Envineer'],
    rankTrack: 'combat', promAttr: 'str',
    gearSlots: [
      { picks: ['Assault rifle', 'LMG', 'ATRL'], reloads: 6 },
      { picks: ['Flak jacket and helmet'] },
      { picks: ['Knife', 'D6 hand grenades'] },
      { picks: ['Personal medkit'] },
      { picks: ['Backpack'] },
    ] },
  { id: 'combatSupport', group: 'military', name: 'Combat Support', military: true,
    blurb: 'Engineers, signal corps — the work behind the lines.',
    req: { int: 10 }, reqLabel: 'INT B+',
    skills: ['survival', 'tech', 'recon'],
    specialties: ['Intelligence', 'Linguist', 'Communications', 'NBC', 'Psy Ops', 'Interrogator'],
    rankTrack: 'combatSupport', promAttr: 'int',
    gearSlots: [
      { picks: ['Assault rifle'], reloads: 6 },
      { picks: ['Flak jacket and helmet'] },
      { picks: ['Knife', 'D6 hand grenades'] },
      { picks: ['Personal medkit'] },
      { picks: ['MOPP suit', 'Manpack radio'] },
      { picks: ['Backpack'] },
    ] },
  { id: 'css', group: 'military', name: 'Combat Service Support', military: true,
    blurb: 'Truckers, mechanics, cooks. The army runs on its stomach.',
    req: {}, reqLabel: 'No requirement',
    skills: ['tech', 'medicalAid'],
    specialties: ['Mechanic', 'Gunsmith', 'Electrician', 'Computers', 'Combat Medic', 'Field Surgeon'],
    rankTrack: 'logistics', promAttr: 'emp',
    gearSlots: [
      { picks: ['Assault rifle'], reloads: 6 },
      { picks: ['Flak jacket and helmet'] },
      { picks: ['Knife', 'D6 hand grenades'] },
      { picks: ['Personal medkit'] },
      { picks: ['Basic tools'] },
      { picks: ['Vehicle tools', 'Weapon tools', 'Surgical instruments'] },
    ] },
  { id: 'special', group: 'military', name: 'Special', military: true,
    blurb: 'Rangers, SAS, Spetsnaz. Quiet professionals.',
    req: { str: 10, agl: 10 }, reqLabel: 'STR B+ and AGL B+',
    termReq:{careers: ['combatArms'], count: 1, label: '1+ term as Combat Arms' },
    skills: ['closeCombat', 'rangedCombat', 'recon', 'survival'],
    specialties: ['Paratrooper', 'Ranger', 'Infiltrator', 'Combat Awareness', 'Sniper', 'SERE Training'],
    rankTrack: 'specOps', promAttr: 'agl',
    gearSlots: [
      { picks: ['Assault rifle', 'Sniper rifle'], reloads: 6 },
      { picks: [
          'Any pistol',
          { text: 'D6 hand grenades', weapon: false },
          { text: 'Rifle-mounted grenade launcher', weapon: false },
        ], reloads: 6 },
      { picks: ['Binoculars', 'Night vision goggles'] },
      { picks: ['Flak jacket and helmet'] },
      { picks: ['Personal medkit'] },
      { picks: ['Backpack'] },
    ] },
  { id: 'officer', group: 'military', name: 'Officer', military: true,
    blurb: 'Lieutenant or above. You lead from the front.',
    req: {  str: 8, agl: 8, int: 10, emp: 8 }, reqLabel: 'INT B+',
    skills: ['command', 'rangedCombat', 'persuasion'],
    specialties: ['Sidearms', 'Intelligence', 'Tactician', 'Logistician', 'Frontline Leader', 'Quartermaster'],
    rankTrack: 'officer', promAttr: 'int',
    gearSlots: [
      { picks: ['Pistol', 'Submachine gun'], reloads: 6 },
      { picks: ['Manpack radio', 'Night vision goggles'] },
      { picks: ['Flak jacket'] },
      { picks: ['Knife', 'D6 hand grenades'] },
      { picks: ['Personal medkit'] },
    ] },

  // === POLICE =============================================================
  { id: 'policeOfficer', group: 'police', name: 'Police Officer', military: false,
    blurb: 'Beat cop. The badge, the radio, the long shift.',
    req: { str: 8, agl: 8, int: 8, emp: 8 }, reqLabel: 'No attribute at D',
    termReq: { exclude: ['prisoner'], label: 'no terms as Prisoner' },
    skills: ['closeCombat', 'rangedCombat'],
    specialties: ['Sidearms', 'Melee', 'Runner', 'Racer', 'Biker', 'Scout'],
    promAttr: 'emp',
    gearSlots: [
      { picks: ['Pistol'], reloads: 6 },
      { picks: ['Handcuffs'] },
      { picks: ['Baton (club)'] },
      { picks: ['Patrol car with half a tank of gasoline'] },
    ] },
  { id: 'detective', group: 'police', name: 'Detective', military: false,
    blurb: 'You follow the threads to where they lead.',
    req: { int: 10 }, reqLabel: 'EMP B+',
    termReq: { careers: ['policeOfficer'], count: 1, label: '1+ term as Police Officer' },
    skills: ['recon', 'rangedCombat', 'closeCombat'],
    specialties: ['Infiltrator', 'Interrogator', 'Intelligence', 'Investigator', 'Locksmith', 'Linguist'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Pistol'], reloads: 6 },
      { picks: ['Lockpicks'] },
    ] },
  { id: 'swat', group: 'police', name: 'SWAT', military: false,
    blurb: 'Special Weapons and Tactics. The cops other cops call.',
    req: { str: 10, agl: 10 }, reqLabel: 'STR B+ and AGL B+',
    termReq: { careers: ['policeOfficer'], count: 1, label: '1+ term as Police Officer' },
    skills: ['closeCombat', 'rangedCombat', 'recon'],
    specialties: ['Martial Artist', 'Rifleman', 'Sniper', 'Combat Awareness', 'Infiltrator', 'Scout'],
    promAttr: 'agl',
    gearSlots: [
      { picks: ['Assault rifle', 'Submachinegun'], reloads: 6 },
      { picks: ['Night vision goggles'] },
      { picks: ['Flak jacket and helmet'] },
      { picks: ['Knife'] },
      { picks: ['Personal medkit'] },
    ] },

  // === CRIME ==============================================================
  { id: 'gangMember', group: 'crime', name: 'Gang Member', military: false,
    blurb: 'Loyalty to colors, settled in blood.',
    req: { str: 8, agl: 8}, reqLabel: 'STR and AGL C+',
    skills: ['closeCombat', 'rangedCombat'],
    specialties: ['Brawler', 'Melee', 'Killer', 'Martial Artist', 'Rifleman', 'Sideamrs'],
    promAttr: 'str',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 6 },
      { picks: ['Knife'] },
    ] },
  { id: 'burglar', group: 'crime', name: 'Burglar', military: false,
    blurb: 'Locks were just polite suggestions.',
    req: { agl: 8, int:8 }, reqLabel: 'AGL AND INT C+',
    skills: ['recon'],
    specialties: ['Brawler', 'Sidearms', 'Mountaineer', 'Infiltrator', 'Electrician', 'Locksmith'],
    promAttr: 'agl',
    gearSlots: [
      { picks: ['Pistol', 'Revolver'], reloads: 6 },
      { picks: ['Lockpick set (TECH +2)'] },
    ] },
  { id: 'hustler', group: 'crime', name: 'Hustler', military: false,
    blurb: 'You always had an angle. Fixer, smuggler, dealer.',
    req: { int: 8, emp: 8 }, reqLabel: 'INT and EMP C+',
    skills: ['persuasion', 'recon'],
    specialties: ['Sidearms', 'Infiltrator', 'Scout', 'Interrogator', 'Psy Ops', 'Trader'],
    promAttr: 'emp',
    gearSlots: [
      { picks: ['Pistol', 'Revolver'], reloads: 6 },
    ] },
  { id: 'prisoner', group: 'crime', name: 'Prisoner', military: false,
    blurb: 'You did time. You came out different.',
    req: {}, reqLabel: 'No requirement',
    skills: ['closeCombat'],
    specialties: ['Brawler', 'Melee', 'Killer', 'Ranger', 'SERE Training', 'Scrounger'],
    promAttr: 'str',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 6 },
      { picks: ['Knife'] },
    ] },

  // === INTELLIGENCE =======================================================
  { id: 'agent', group: 'intel', name: 'Agent', military: true,
    blurb: 'KGB, CIA, GRU, MI6. The grey work.',
    req: { int: 10 }, reqLabel: 'INT B+',
    skills: ['recon', 'persuasion', 'rangedCombat'],
    specialties: ['Intelligence', 'Locksmith', 'Investigator', 'Scout', 'Psy Ops', 'Sidearms'],
    rankTrack: 'intel', promAttr: 'int',
    gearSlots: [
      { picks: ['Pistol'], reloads: 6 },
      { picks: ['Lockpick set'] },
      { picks: ['Knife', 'Explosives'] },
      { picks: ['Personal medkit'] },
    ] },
  { id: 'assassin', group: 'intel', name: 'Assassin', military: true,
    blurb: 'You do what cannot be done in daylight.',
    req: { agl: 10 }, reqMax:{emp:8}, reqLabel: 'AGL B+, EMP D or C',
    termReq: { careers: ['agent'], count: 1, label: '1+ term as Agent' },
    skills: ['rangedCombat', 'closeCombat'],
    specialties: ['Killer', 'Interrogator', 'Sniper',  'Martial Artist', 'Improvised Munitions', 'Infiltrator'],
    rankTrack: 'intel', promAttr: 'agl',
    gearSlots: [
      { picks: ['Sniper rifle (suppressed)', 'Submachinegun (suppressed)'], reloads: 6 },
      { picks: ['Radio', 'Binoculars'] },
      { picks: ['Knife', 'Explosives'] },
      { picks: ['Personal medkit'] },
    ] },
  { id: 'paramilitary', group: 'intel', name: 'Paramilitary', military: true,
    blurb: 'Agency soldiers. Black ops in foreign mud.',
    req: { str: 10, agl:10 }, reqLabel: 'STR and AGL B+',
    termReq: { group: 'military', count: 1, label: '1+ term in Military' },
    skills: ['rangedCombat', 'heavyWeapons', 'survival'],
    specialties: ['Brawler', 'Rifleman', 'Machinegunner', 'Combat Engineer', 'Improvised Munitions', 'Tactician'],
    rankTrack: 'specOps', promAttr: 'str',
    gearSlots: [
      { picks: ['Assault rifle', 'LMG', 'ATRL'], reloads: 6 },
      { picks: ['Knife', 'D6 hand grenades'] },
      { picks: ['Personal medkit'] },
    ] },

  // === BLUE COLLAR ========================================================
  { id: 'driver', group: 'blueCollar', name: 'Driver', military: false,
    blurb: 'You knew every back road. The cargo got there.',
    req: {agl: 10}, reqLabel: 'AGL B+',
    skills: ['tech'],
    specialties: ['Biker', 'Boatman', 'Navigator', 'Pilot', 'Racer', 'Tanker'],
    promAttr: 'agl',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Any civilian car or truck'] },
      { picks: ['Vehicle tools'] },
    ] },
  { id: 'farmer', group: 'blueCollar', name: 'Farmer', military: false,
    blurb: 'You knew weather and animals before you knew much else.',
    req: {}, reqLabel: 'No requirement',
    skills: ['survival'],
    specialties: ['Cook', 'Farmer', 'Fisher', 'Hunter', 'Forager', 'Rider'],
    promAttr: 'emp',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Pickup truck'] },
      { picks: ['Basic toolkit'] },
      { picks: ['2D6 rations of food'] },
    ] },
  { id: 'mechanic', group: 'blueCollar', name: 'Mechanic', military: false,
    blurb: 'You could fix anything with enough wire and patience.',
    req: {}, reqLabel: 'No requirement',
    skills: ['tech'],
    specialties: ['Blacksmith', 'Gunsmith', 'Locksmith', 'Mechanic', 'Scrounger', 'Improvised Munitions'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Pickup truck'] },
      { picks: ['Basic tools'] },
      { picks: ['Vehicle tools', 'Weapon tools'] },
    ] },
  { id: 'construction', group: 'blueCollar', name: 'Construction', military: false,
    blurb: 'Hard hat, harder back. You built and rebuilt.',
    req: { str: 10 }, reqLabel: 'STR B+',
    skills: ['closeCombat', 'tech'],
    specialties: ['Brawler', 'Builder', 'Load Carrier', 'Blacksmith', 'Electrician', 'Improvised Munitions'],
    promAttr: 'str',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Crowbar'] },
      { picks: ['Pickup truck'] },
      { picks: ['Basic tools'] },
    ] },

  // === EDUCATION ==========================================================
  { id: 'liberalArts', group: 'education', name: 'Liberal Arts', military: false,
    blurb: 'Books were the place you went when the world got too loud.',
    req: { int: 8, emp: 8 }, reqLabel: 'INT and Emp C+',
    skills: ['persuasion'],
    specialties: ['Historian', 'Cook', 'Linguist', 'Musician', 'Psy Ops', 'Councilor'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Dictionary in any language'] },
      { picks: ['Bicycle'] },
    ] },
  { id: 'sciences', group: 'education', name: 'Sciences', military: false,
    blurb: 'Lab benches, late nights, the satisfaction of the model fitting.',
    req: { int: 10 }, reqLabel: 'INT B+',
    skills: ['tech'],
    specialties: ['Chemist', 'Communication', 'Computers', 'Electrician', 'Scientist', 'Linguist'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Bicycle', '2WD car with half a tank of gasoline'] },
    ] },

  // === WHITE COLLAR =======================================================
  { id: 'doctor', group: 'whiteCollar', name: 'Doctor', military: false,
    blurb: 'Hospitals or clinics, you patched what you could.',
    req: { int: 10 }, reqLabel: 'INT B+',
    termReq: { careers: ['sciences'], count: 2, label: '2 terms in Sciences' },
    skills: ['medicalAid','persuasion'],
    specialties: ['Linguist', 'Combat Medic', 'Counselor', 'Field Surgeon', 'General Practioner', 'Veterinarian'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['D6 personal medkits'] },
      { picks: ['Pain relievers'] },
      { picks: ['Surgical instruments'] },
    ] },
  { id: 'professor', group: 'whiteCollar', name: 'Professor', military: false,
    blurb: 'Tenure track, lecture halls, the long argument.',
    req: { int: 10 }, reqLabel: 'INT B+',
    termReq: { careers: ['liberalArts'], count: 2, label: '2 terms in Liberal Arts' },
    skills: ['persuasion'],
    specialties: ['Historian', 'Chemist', 'Scientist', 'Linguist', 'Psy Ops', 'Teacher'],
    promAttr: 'int',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['2WD car with half a tank of gasoline'] },
    ] },
  { id: 'manager', group: 'whiteCollar', name: 'Manager', military: false,
    blurb: 'Suits, spreadsheets, the slow gears of organization.',
    req: { emp: 8, int: 10 }, reqLabel: 'EMP C+ and INT B+',
    termReq: { careers: ['liberalArts', 'sciences'], count: 1, label: '1+ term in Education' },
    skills: ['persuasion', 'command', 'tech'],
    specialties: ['Quartermaster', 'Computers', 'Frontline Leader', 'Logistician', 'Teacher', 'Counselor'],
    promAttr: 'emp',
    gearSlots: [
      { picks: ['Any civilian firearm'], reloads: 3 },
      { picks: ['Pocket calculator'] },
      { picks: ['2WD car with half a tank of gasoline'] },
    ] },
];

// At War specialty tables, one D6 column per most-recent-career group.
// The "Other" column has 5 entries per the transcription; result 6 falls back
// to the last entry (Improvised Munitions) until the missing entry surfaces.
export const AT_WAR_SPECIALTIES = {
  military:    ['Brawler', 'Ranger', 'NBC', 'Rifleman', 'Scrounger', 'Improvised Munitions'],
  blueCollar:  ['Brawler', 'Rider', 'Runner', 'Quartermaster', 'Gunsmith', 'Mechanic'],
  whiteCollar: ['Scout', 'Fisher', 'Forager', 'Scrounger', 'Frontline Leader', 'Interrogator'],
  other:       ['Racer', 'Hunter', 'Forager', 'Quartermaster', 'Improvised Munitions', 'Improvised Munitions'],
};

// Map career group → which At War specialty column to use. Police, Crime,
// and Intelligence land in "Other"; Education rolls academically as White
// Collar; Blue Collar and Military map 1:1.
export const AT_WAR_COLUMN = {
  military:    'military',
  blueCollar:  'blueCollar',
  whiteCollar: 'whiteCollar',
  education:   'whiteCollar',
  police:      'other',
  crime:       'other',
  intel:       'other',
};
